### ISSUE TITLE
More Cron Documentation?

### ISSUE THREAD

**Issue by Scribbler2099** [guruevi/CiviGroupSync#2]
I've been using this manually and it works well for ACL's, but I was hoping there might be some more Documentation on how to set up a Cron to run this.

**Comment by guruevi** [comment]
Hi, Cron is actually part of your Linux distribution. Some Linux systems may use another scheduler or even systemd timers to schedule so it's not universal but there is some excellent documentation here which you should probably review given you are using Drupal: https://www.drupal.org/docs/7/setting-up-cron-for-drupal/configuring-cron-jobs-using-the-cron-command and http://docs.drush.org/en/master/cron/

Once you've step up a "general cron" for your site, you can then in similar syntax add the drush command you've been typing in so far. Eg.
<code>10 * * * * /usr/bin/env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin COLUMNS=72 cd [DOCROOT] && ../vendor/bin/drush --uri=your.drupalsite.org --quiet civigroup-sync 5 12</code>
